version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: user-management-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: user_management
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - user-management-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  user-management-network:
    driver: bridge
